export { default as UsersList } from "./users";
export { default as RoutesList } from "./routes";
export { default as AirLinesList } from "./airlines";
export { default as TransactionsList } from "./transactions";
export { default as PromosList } from "./promos";
export { default as FlightSchedulesList } from "./flightSchedules";
export { default as OrdersList } from "./orders";
export { default as AirportsList } from "./airports";
export { default as DashboardList } from "./dashboard";
